### ISSUE TITLE
Crash In staging-3.0.0 in playcover.toucher Queue

### ISSUE THREAD

**Issue by lastMove** [PlayCover/PlayTools#96] opened 2023-03-07 04:55 UTC
Hello, 

I noticed a regression. There is a crash in the func  `touchcam(point: CGPoint, phase: UITouch.Phase, tid: inout Int?)`

It happens to me, systematically after playing for a minute. it's an out of range error.
I ran it using gdb here are the logs: 

````
Swift/ContiguousArrayBuffer.swift:613: Fatal error: Index out of range
2023-03-07 05:16:59.368651+0100 RL2DClient[56230:1628919] Swift/ContiguousArrayBuffer.swift:613: Fatal error: Index out of range
Process 56230 stopped
* thread #59, queue = 'playcover.toucher', stop reason = Fatal error: Index out of range
    frame #0: 0x00000001aee6cae8 libswiftCore.dylib`_swift_runtime_on_report
libswiftCore.dylib`:
->  0x1aee6cae8 <+0>: ret    

libswiftCore.dylib`:
    0x1aee6caec <+0>: b      0x1aee6cae8               ; _swift_runtime_on_report

libswiftCore.dylib`:
    0x1aee6caf0 <+0>: adrp   x8, 307987
    0x1aee6caf4 <+4>: ldrb   w0, [x8, #0x6fc]
Target 0: (RL2DClient) stopped.
Process 56230 launched: '/Users/jasonakakpo/Library/Containers/io.playcover.PlayCover/RL Sideswipe.app/RL2DClient' (arm64)
(lldb) exit
````
 
Looks to me that it related to this: 
```swift
            let resultingId = PTFakeMetaTouch.fakeTouchId(pointId, at: point, with: phase, in: keyWindow, on: keyView)
            if resultingId < 0 {
                idMap[pointId] = nil
            } else {
                idMap[resultingId] = bigId
            }
```

PTFakeMetaTouch may returns an index > 64 which is the fixed size of the idMap array. 
I guess this situation should not happen (we should not need more than 64 different IDs), but maybe we can fix it by using a [Int:Int] dictionary  instead of the [Int?] array for idMap.

**Comment by XuYicong** [comment] 2023-03-07 09:04
Hello, yes, there is something wrong with that part.

Generally it's a bad idea to seperate the work into two threads at that part. So what I'm trying to do is, putting the whole `Toucher.touch()` function into that `playcover.toucher` queue, so that it doesn't need to translate IDs there.

Had been implemented in #88 but not merged yet.

**Comment by lastMove** [comment] 2023-03-07 11:31
Ok, perfect then.

**Comment by lastMove** [comment] 2023-03-07 18:41
I tried #88 it works greatly and the mapping seems more reactive.

**Comment by XuYicong** [comment] 2023-03-08 06:17
Do you notice any issue with that PR? The reason it is not merged yet is that people noticed random weird behaviours with it, which I cannot reproduce. I am looking forward to more people testing it.

**Comment by lastMove** [comment] 2023-03-09 14:07
On my side it's working quite well, the things I noticed: 

- I  have a Toast showing up each time I press a controller key this one I guess:             `Toast.showOver(msg: name + ": \(buttonElement.isPressed)")`
- I have to press control+Option to trigger the apple Touch alternatives. (instead of just Option). 

On the other side, now I can assign the same Controller button to multiple Keymap and it works perfectly, which is huge for me, And PlayChain works! 

What are the issues reported? so I can check if I repro it on my side

**Comment by XuYicong** [comment] 2023-03-09 15:55
> I have a Toast showing up each time I press a controller key, this one I guess: Toast.showOver(msg: name + ": \(buttonElement.isPressed)")

OMG I forgot to delete that debug output lmao
> I have to press control+Option to trigger the apple Touch alternatives. (instead of just Option)

Can Touch alternatives be triggered by Option? I didn't know that lol

It is reported that sometimes when pressing Enter/Return to send chat messages in some games, that message would be sent multiple times.

**Comment by lastMove** [comment] 2023-03-13 03:38
Thanks! I pulled your new changes and it works great. I don't have the Enter/Return bug for chat messages on my side.

**Comment by lastMove** [comment] 2023-03-13 04:35
Btw I noticed that if I open an app and then turn on my Controller, my controller won't be bound. I need to open Keymap editor and close it to trigger the saving of the map. 
After checking the code it looks like it is a regression: 
I fixed it, I tested it it works for me now, I created a PR to your branch: 
https://github.com/XuYicong/PlayTools/pull/2

**Comment by XuYicong** [comment] 2023-03-13 09:12
Thanks for contributing! Testing on controller mapping is indeed not enough. Feel free to fix things if you notice more!

**Closed** 2023-05-03 19:44 UTC
